INSERT INTO openmrs.patient_identifier_type 
			(patient_identifier_type_id,
			name,
			description,
			format,
			check_digit,
			creator,
			date_created,
			required,
			format_description,
			validator,
			retired,
			retired_by,
			date_retired,
			retire_reason,
			uuid,
			location_behavior,
			uniqueness_behavior) 
VALUES 		(15,
			'NID (DISA)',
			'Numero de Identificaçao de Doente, serviço DISA',
			'[0-9]{10}/[0-9]{4}/[0-9]{5}',
			0,
			13,
			'2020-08-20 09:04:10',
			0,
			'PPDDUUSS/AA/NNNNN',
			null,
			0,
			null,
			null,
			null,
			'a31d7b5c-eafb-4bde-86c5-cb05ce29c240',
			null,
			null);